// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  portfolioId: __t.u64().name("portfolio_id"),
  symbol: __t.string(),
  percentage: __t.f64(),
  limit: __t.f64(),
  exposureValue: __t.f64().name("exposure_value"),
  portfolioValue: __t.f64().name("portfolio_value"),
  createdAt: __t.timestamp().name("created_at"),
});
