// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Asset = __t.object("Asset", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  assetType: __t.string(),
  portfolioId: __t.u64(),
});
export type Asset = __Infer<typeof Asset>;

export const EtfHolding = __t.object("EtfHolding", {
  key: __t.string(),
  etfSymbol: __t.string(),
  holdingSymbol: __t.string(),
  holdingName: __t.string(),
  weight: __t.f64(),
});
export type EtfHolding = __Infer<typeof EtfHolding>;

export const ExposureBreach = __t.object("ExposureBreach", {
  key: __t.string(),
  portfolioId: __t.u64(),
  symbol: __t.string(),
  percentage: __t.f64(),
});
export type ExposureBreach = __Infer<typeof ExposureBreach>;

export const ExposureLimit = __t.object("ExposureLimit", {
  portfolioId: __t.u64(),
  maximumPercentage: __t.f64(),
});
export type ExposureLimit = __Infer<typeof ExposureLimit>;

export const ExposureWarning = __t.object("ExposureWarning", {
  id: __t.u64(),
  portfolioId: __t.u64(),
  symbol: __t.string(),
  percentage: __t.f64(),
  limit: __t.f64(),
  exposureValue: __t.f64(),
  portfolioValue: __t.f64(),
  createdAt: __t.timestamp(),
});
export type ExposureWarning = __Infer<typeof ExposureWarning>;

export const ImportedEtfHolding = __t.object("ImportedEtfHolding", {
  symbol: __t.string(),
  name: __t.string(),
  weight: __t.f64(),
});
export type ImportedEtfHolding = __Infer<typeof ImportedEtfHolding>;

export const MyAssets = __t.object("MyAssets", {});
export type MyAssets = __Infer<typeof MyAssets>;

export const MyEtfHoldings = __t.object("MyEtfHoldings", {});
export type MyEtfHoldings = __Infer<typeof MyEtfHoldings>;

export const MyExposureLimit = __t.object("MyExposureLimit", {});
export type MyExposureLimit = __Infer<typeof MyExposureLimit>;

export const MyExposureWarnings = __t.object("MyExposureWarnings", {});
export type MyExposureWarnings = __Infer<typeof MyExposureWarnings>;

export const MyPortfolio = __t.object("MyPortfolio", {});
export type MyPortfolio = __Infer<typeof MyPortfolio>;

export const MyPositions = __t.object("MyPositions", {});
export type MyPositions = __Infer<typeof MyPositions>;

export const MyPrices = __t.object("MyPrices", {});
export type MyPrices = __Infer<typeof MyPrices>;

export const MyRealPriceFeed = __t.object("MyRealPriceFeed", {});
export type MyRealPriceFeed = __Infer<typeof MyRealPriceFeed>;

export const MyTestPriceFeed = __t.object("MyTestPriceFeed", {});
export type MyTestPriceFeed = __Infer<typeof MyTestPriceFeed>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const Portfolio = __t.object("Portfolio", {
  id: __t.u64(),
});
export type Portfolio = __Infer<typeof Portfolio>;

export const PortfolioAccess = __t.object("PortfolioAccess", {
  identity: __t.identity(),
  portfolioId: __t.u64(),
});
export type PortfolioAccess = __Infer<typeof PortfolioAccess>;

export const PortfolioCredential = __t.object("PortfolioCredential", {
  tokenId: __t.string(),
  portfolioId: __t.u64(),
  salt: __t.string(),
  tokenHash: __t.string(),
});
export type PortfolioCredential = __Infer<typeof PortfolioCredential>;

export const PortfolioEtfHolding = __t.object("PortfolioEtfHolding", {
  key: __t.string(),
  portfolioId: __t.u64(),
  etfSymbol: __t.string(),
  holdingSymbol: __t.string(),
  holdingName: __t.string(),
  weight: __t.f64(),
  source: __t.string(),
  fetchedAt: __t.timestamp(),
});
export type PortfolioEtfHolding = __Infer<typeof PortfolioEtfHolding>;

export const Position = __t.object("Position", {
  id: __t.u64(),
  owner: __t.identity(),
  assetId: __t.u64(),
  amount: __t.f64(),
  purchasePrice: __t.f64(),
  portfolioId: __t.u64(),
});
export type Position = __Infer<typeof Position>;

export const Price = __t.object("Price", {
  assetId: __t.u64(),
  portfolioId: __t.u64(),
  value: __t.f64(),
  updatedAt: __t.timestamp(),
  change: __t.f64(),
  source: __t.string(),
});
export type Price = __Infer<typeof Price>;

export const RealPriceFeed = __t.object("RealPriceFeed", {
  portfolioId: __t.u64(),
  isRunning: __t.bool(),
  lastAttemptAt: __t.option(__t.timestamp()),
  lastSuccessAt: __t.option(__t.timestamp()),
  message: __t.string(),
});
export type RealPriceFeed = __Infer<typeof RealPriceFeed>;

export const RealPriceTick = __t.object("RealPriceTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  portfolioId: __t.u64(),
});
export type RealPriceTick = __Infer<typeof RealPriceTick>;

export const RefreshResult = __t.object("RefreshResult", {
  updated: __t.u32(),
  failed: __t.u32(),
  message: __t.string(),
});
export type RefreshResult = __Infer<typeof RefreshResult>;

export const TestPriceFeed = __t.object("TestPriceFeed", {
  portfolioId: __t.u64(),
  isRunning: __t.bool(),
});
export type TestPriceFeed = __Infer<typeof TestPriceFeed>;

export const TestPriceTick = __t.object("TestPriceTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  portfolioId: __t.u64(),
});
export type TestPriceTick = __Infer<typeof TestPriceTick>;
