// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import AddPositionReducer from "../add_position_reducer";
import AuthenticatePortfolioReducer from "../authenticate_portfolio_reducer";
import CreatePortfolioReducer from "../create_portfolio_reducer";
import LogoutPortfolioReducer from "../logout_portfolio_reducer";
import RemovePositionReducer from "../remove_position_reducer";
import SayHelloReducer from "../say_hello_reducer";
import SetPriceReducer from "../set_price_reducer";
import StartTestPricesReducer from "../start_test_prices_reducer";
import StopTestPricesReducer from "../stop_test_prices_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type AddPositionParams = __Infer<typeof AddPositionReducer>;
export type AuthenticatePortfolioParams = __Infer<typeof AuthenticatePortfolioReducer>;
export type CreatePortfolioParams = __Infer<typeof CreatePortfolioReducer>;
export type LogoutPortfolioParams = __Infer<typeof LogoutPortfolioReducer>;
export type RemovePositionParams = __Infer<typeof RemovePositionReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type SetPriceParams = __Infer<typeof SetPriceReducer>;
export type StartTestPricesParams = __Infer<typeof StartTestPricesReducer>;
export type StopTestPricesParams = __Infer<typeof StopTestPricesReducer>;
