// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import AddPositionReducer from "../add_position_reducer";
import AuthenticatePortfolioReducer from "../authenticate_portfolio_reducer";
import CreatePortfolioReducer from "../create_portfolio_reducer";
import LoadSampleEtfHoldingsReducer from "../load_sample_etf_holdings_reducer";
import LogoutPortfolioReducer from "../logout_portfolio_reducer";
import RemoveMarketDataCredentialReducer from "../remove_market_data_credential_reducer";
import RemovePositionReducer from "../remove_position_reducer";
import ReplaceEtfHoldingsReducer from "../replace_etf_holdings_reducer";
import SayHelloReducer from "../say_hello_reducer";
import SetExposureLimitReducer from "../set_exposure_limit_reducer";
import SetMarketDataCredentialReducer from "../set_market_data_credential_reducer";
import SetPriceReducer from "../set_price_reducer";
import StartRealPricesReducer from "../start_real_prices_reducer";
import StartTestPricesReducer from "../start_test_prices_reducer";
import StopRealPricesReducer from "../stop_real_prices_reducer";
import StopTestPricesReducer from "../stop_test_prices_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type AddPositionParams = __Infer<typeof AddPositionReducer>;
export type AuthenticatePortfolioParams = __Infer<typeof AuthenticatePortfolioReducer>;
export type CreatePortfolioParams = __Infer<typeof CreatePortfolioReducer>;
export type LoadSampleEtfHoldingsParams = __Infer<typeof LoadSampleEtfHoldingsReducer>;
export type LogoutPortfolioParams = __Infer<typeof LogoutPortfolioReducer>;
export type RemoveMarketDataCredentialParams = __Infer<typeof RemoveMarketDataCredentialReducer>;
export type RemovePositionParams = __Infer<typeof RemovePositionReducer>;
export type ReplaceEtfHoldingsParams = __Infer<typeof ReplaceEtfHoldingsReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type SetExposureLimitParams = __Infer<typeof SetExposureLimitReducer>;
export type SetMarketDataCredentialParams = __Infer<typeof SetMarketDataCredentialReducer>;
export type SetPriceParams = __Infer<typeof SetPriceReducer>;
export type StartRealPricesParams = __Infer<typeof StartRealPricesReducer>;
export type StartTestPricesParams = __Infer<typeof StartTestPricesReducer>;
export type StopRealPricesParams = __Infer<typeof StopRealPricesReducer>;
export type StopTestPricesParams = __Infer<typeof StopTestPricesReducer>;
